# Generated by Django 4.2.16 on 2024-12-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tebak_angka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, default=4000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tebak_angka.uploadedphoto')),
            ],
        ),
    ]
