# Generated by Django 4.2.16 on 2024-12-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tebak_angka', '0002_predictionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
